package Exception1;
import java.util.*;
public class Exception1_1 {
Scanner a=new Scanner(System.in);
double b;
final double exp=0.0000001;
	int readKeyBoardInt()
	{
		try {
			b=a.nextDouble();
			if(b-(int)b>exp) throw new NumberFormatException();
		}
		catch(NumberFormatException er){
			System.out.println(";此时数据为：";+b+";浮点数\;n";+";请重新输入！";);
			b=a.nextDouble();
		}
		return (int)b;
	}
	void exp()
	{
		try {
			b=a.nextDouble();
			if(b-exp>0) throw new NumberFormatException();
			else System.out.println(";无异常";);
		}
		catch(NumberFormatException u)
		{
			System.out.println(";有异常，崩溃了我！";);
		}
	}
}


package Exception1;
import java.util.*;
public class MyException extends Exception1_1{
String fault_massege;
Scanner a=new Scanner(System.in);
	public MyException()
	{
		fault_massege=";不知道咋错了";;
	}
	public MyException(String fault_massege)
	{
		this.fault_massege=fault_massege;
	}
	int apporch()
	{
		int i=100;
		double x=a.nextDouble();
		try{
			if(x-exp<0) throw new NumberFormatException();
			else if(x>1) throw new Exception();
		}
		catch(NumberFormatException e){
			System.out.println(this.fault_massege+";x<0";);
		}
		catch(Exception e){
			System.out.println(this.fault_massege+";x>1";);
		}
		while(i*x-0.1-exp>0)
		{
			i--;
		}
		return i;
	}
}


package Exception1;

public class Test {
 public static void main(String[] args)
 {
	 int q=0;
//	 Exception1_1 test1=new Exception1_1();
//	 q=test1.readKeyBoardInt();
//	 System.out.println(q);
	 MyException ww=new MyException(";我错了！";);
	 q=ww.apporch();
	 System.out.println(q);
 }
}
 